name: "Coverage Report for lcov format with monorepo context support personalized"
description: "Comments a pull request with code coverage"
author: "Forked from: nohmand"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
